# Generated by Django 5.2.13 on 2026-04-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frame_type', models.CharField(choices=[('round', 'Round'), ('oval', 'Oval'), ('square', 'Square')], max_length=20)),
                ('price', models.FloatField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
